In [26]:
# What does a neuron compute?

# A neuron computes a linear function (z = Wx + b) followed by an activation function

In [27]:
#Which of these is the "Logistic Loss"?

# L(i)(y^(i),y(i))=−(y(i)log(y^(i))+(1−y(i))log(1−y^(i)))

In [28]:
# Suppose img is a (32,32,3) array, representing a 32x32 image with 3 color channels red, 
# green and blue. How do you reshape this into a column vector?
#x = img.reshape((32*32*3,1))

#Example below:

import numpy as np
A = np.array([[1,1,1],[1,1,1]])
B = np.array([[2,2,2],[2,2,2]])
C=np.array([[3,3,3],[3,3,3]])
print(A) 
print(B) 
print(C)

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[3 3 3]
 [3 3 3]]


In [29]:
A.shape

(2, 3)

In [30]:
A.reshape((2*3),1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [31]:
# Consider the two following random arrays "a" and "b":
# What will be the shape of "c"?

a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [32]:
c.shape

(2, 3)

In [33]:
#Consider the two following random arrays "a" and "b":
#What will be the shape of "c"?

a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)

In [35]:
# c = a*b # will give error

In [36]:
# Suppose you have nx input features per example. Recall that X=[x(1)x(2)...x(m)]. What is the dimension of X?
#(nx,m)

In [37]:
# Recall that "np.dot(a,b)" performs a matrix multiplication on a and b, whereas "a*b" performs an element-wise multiplication.
#Consider the two following random arrays "a" and "b":

a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [38]:
c.shape

(12288, 45)

In [41]:
# Consider the following code snippet:

# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3,4)
b = np.random.randn(4,1)

#for i in range(3):
#    for j in range(4):
#        c[i][j] = a[i][j] + b[j]
        
        
# How do you vectorize this?
#c = a + b.T
c = a+np.transpose(b)
print(c)

[[-2.9470033   0.03258165 -0.24649538  0.0696474 ]
 [-1.95909138 -0.76673299  0.10673108 -0.16879477]
 [-2.08600594  0.1000894  -1.56071474  0.66375689]]


In [43]:
# Consider the following code:
#What will be c? (If you’re not sure, feel free to run this in python to find out).

a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

# This will invoke broadcasting, so b is copied three times to become (3,3), and ∗ is an 
# element-wise product so c.shape will be (3, 3)

(3, 3)

In [45]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a+b

In [46]:
c.shape

(2, 3)