In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
b = np.random.randn(5,1)

In [4]:
a

array([-0.1490545 , -0.78355293,  0.8810587 ,  2.41115034,  0.2343375 ])

In [5]:
b

array([[ 0.66251315],
       [ 0.40305177],
       [ 0.43425122],
       [ 1.25716778],
       [-0.82404036]])

In [6]:
np.dot(a, a.T)

7.2809969020020073

In [7]:
np.dot(b, b.T)

array([[ 0.43892367,  0.2670271 ,  0.28769714,  0.83289018, -0.54593757],
       [ 0.2670271 ,  0.16245073,  0.17502572,  0.5067037 , -0.33213093],
       [ 0.28769714,  0.17502572,  0.18857412,  0.54592664, -0.35784053],
       [ 0.83289018,  0.5067037 ,  0.54592664,  1.58047082, -1.03595698],
       [-0.54593757, -0.33213093, -0.35784053, -1.03595698,  0.67904251]])

In [ ]:
# Don't use rank 1 array, use matrix